# Generated by Django 5.1.1 on 2024-09-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlenderPathProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=60)),
                ('time_save_project', models.DateTimeField()),
                ('path_save_project', models.TextField()),
            ],
            options={
                'verbose_name': 'Blender project save path',
                'verbose_name_plural': 'Path to save blender projects',
                'db_table': 'blender_path_project',
                'ordering': ['time_save_project'],
            },
        ),
    ]
